name: Laravel Test Action

description: Run tests with specified group
inputs:
  test-group:
    description: 'Group about app (Api, ApiAdmin, Console, etc)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.pipeline', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env.pipeline
      run: \cp -pf .env.pipeline .env

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests
      run: vendor/bin/pest --testsuite=Feature --group=${{ inputs.test-group }} --coverage-clover=coverage.xml
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
