name: Check PHP Upgrades - master

on:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - '.github/workflows/master-rector.yml'
      - 'composer.lock'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run Rector in src
        run: ./vendor/bin/rector process src --dry-run
