name: Run static analysis - master

on:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - '.github/workflows/master-phpstan.yml'
      - 'phpstan.neon'
      - 'composer.lock'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run PHPStan on src
        run: ./vendor/bin/phpstan --error-format=github

      - name: Run PHPStan on tests
        run: ./vendor/bin/phpstan analyse -c phpstan.tests.neon --error-format=github
