name: Check code style - master

on:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - '.github/workflows/master-php-cs-fixer.yml'
      - 'composer.lock'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run PHP cs fixer
        run: ./vendor/bin/php-cs-fixer fix
