name: Check code quality - master

on:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - '.github/workflows/master-php-insights.yml'
      - 'composer.lock'

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - run: composer install --prefer-dist --no-progress --no-suggest
      # TODO: Increase metrics
      - run: vendor/bin/phpinsights --min-quality=85 --min-complexity=85 --min-architecture=75 --min-style=90 -n --ansi --format=github-action
