name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1


      - name: Run PHPStan on src
        run: ./vendor/bin/phpstan --error-format=github

      - name: Run PHPStan on tests
        run: ./vendor/bin/phpstan analyse -c phpstan.tests.neon --error-format=github
